### ISSUE TITLE
file_sync.js file

### ISSUE THREAD

**Issue by eskimos78** [bhazzard/davynci#1]
Dear Brian,
I would like to test your application, in the usage section you wrote "node file_sync.js" is this a typo or am I missing something ?
What npm modules are required by your application?

Thanks and regards.

**Comment by bhazzard** [comment]
I apologize, the usage section is out of date.

The application is actually a desktop application based on the Electron framework.

The package.json file should be up to date with all dependencies. So run "npm install" and you should have everything you need.

Then you just run "electron ." to launch the desktop app.

You can also build distributables with the electron packager: https://github.com/maxogden/electron-packager/blob/master/readme.md

**Comment by eskimos78** [comment]
Dear Brian,
i have installed Electon framework and now your application seems works well but remote changes are not replicated, is it my fault or is a backup and not a sync implementation?
Is possible and how much work to implement syncronization?

Console shows some "deprecated" and "undefined" ininfluent messages:

Thanks and regards.

_Deprecated_

```
$ electron .
(electron) ipc module is deprecated. Use ipcMain module instead.
```

_Undefined_

```
DAVsync started.
http://snip/server.php/snip/file.png
file created: /Users/mypc/Documents/dav/file.png
undefined
{ etag: undefined,
  href: 'http://snip/server.php/snip/file.png' }
```

**Comment by bhazzard** [comment]
Right now it is a one way backup of files. We have started implementing a remote changes sync based on e-tags, but it is on pause right now.

**Comment by eskimos78** [comment]
Dear Brian,
what do you think, how long will it take (work days) for a "regular developer" to implement remote changes sync based on e-tags?

Thanks and Regards.

**Comment by bhazzard** [comment]
I'd love your contribution. Its hard for me to say what level of effort it
would take. I'm guessing it would take several coding sessions to hammer
out the bugs.

Brian Hazzard
